### ISSUE TITLE
Slider should take string and parent instead of QLabel

### ISSUE THREAD

**Issue by lauramurgatroyd** [TomographicImaging/eqt#60]
https://github.com/paskino/qt-elements/blob/main/eqt/ui/UISliderWidget.py

**Comment by jcornall** [comment]
After reviewing pull request [#168](https://github.com/TomographicImaging/eqt/pull/168), it was determined that including a parent parameter in the UISliderWidget's __init__() method would be redundant - this is because the parent() attribute is implicitly set to None when the UISliderWidget is instantiated, and is updated to the FormDialog object when the addWidget() method is called. Because the parent does not need to be explicitly set, this parameter is not required.

**Comment by lauramurgatroyd** [comment]
Sounds good!
